### ISSUE TITLE
Last slide

### ISSUE THREAD

**Issue by gplssm** [rl-institut/beamer_theme#2]
Provide a standard last slide similar to the one of the PPTX template

**Comment by gplssm** [comment]
Basic design of last slide was done in 3a17357dc708eba23d65af088cd269e41d3770ea

Missing stuff (some stuff will be postponed to later versions)

- [x] Font size and font weights
- [x] Exact text positions
- [ ] ~Logo on final slide~
- [ ] ~Shortauthor in pandoc Markdown metadata definieren~ #12 
- [ ]  ~Custom license: overwrite deafult CC-BY 4.0 text and remove logo~ #13
- [ ] ~Define Tel, Email, Twitter, finalstatement in Pandoc metadata and convert it to a LaTeX variable (now in header-includes)~ #12 
- [x] Replace "contact logo" (speech balloons) by logo from RLI PPTX template

**Comment by gplssm** [comment]
For now, no logo on the last slide. Open a new issue for that.
