### ISSUE TITLE
Title page

### ISSUE THREAD

**Issue by gplssm** [rl-institut/beamer_theme#5]
### Tasks

- [x] Use correct font, font weight, and font size
- [x] Position text box "correctly" (the same position as in PPTX)
- [x] Choose good default background image
  If it will be the current one, make sure (a) rights are respected and (b) credits for the image are provided
- [x] Remove unintended vertical line (left border of background image)

### Optional tasks

- [ ] ~Resize boxes to exact same size as in PPTX template~
- [ ] ~Position image overlay according to PPTX template~

**Comment by gplssm** [comment]
Optional tasks won't be done. With communications it was agreed not to stick to strictly to the PPTX template.
